# Generated by Django 6.0.7 on 2026-08-03 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="ISO 3166-1 alpha-2, e.g. 'US'", max_length=2, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='core.country')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('level', models.CharField(choices=[('diploma', 'Diploma / Certificate'), ('bachelors', "Bachelor's"), ('masters', "Master's"), ('phd', 'PhD / Doctorate'), ('postdoc', 'Postdoctoral'), ('any', 'Any Level')], db_index=True, default='any', max_length=20)),
                ('funding_type', models.CharField(choices=[('fully_funded', 'Fully Funded'), ('partially_funded', 'Partially Funded'), ('self_funded', 'Self Funded / Tuition Waiver Only')], db_index=True, default='fully_funded', max_length=20)),
                ('application_fee_required', models.BooleanField(default=False, help_text='Does the applicant need to pay a fee to apply?')),
                ('nationality_scope', models.CharField(choices=[('all', 'Open to All Nationalities'), ('specific', 'Specific Countries Only')], default='all', help_text="Choose 'Specific Countries Only' to restrict eligibility below.", max_length=10)),
                ('university', models.CharField(help_text='University or organization name', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='scholarship_logos/')),
                ('application_link', models.URLField()),
                ('deadline', models.DateField(db_index=True)),
                ('is_active', models.BooleanField(default=True, help_text='Manually unpublish a scholarship without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('eligible_countries', models.ManyToManyField(blank=True, help_text="Leave empty if 'Open to All Nationalities' is selected.", related_name='scholarships', to='core.country')),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='SavedScholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('not_interested', 'Not Interested')], default='saved', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scholarships', to=settings.AUTH_USER_MODEL)),
                ('scholarship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='core.scholarship')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['deadline', 'is_active'], name='core_schola_deadlin_d12c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['level', 'funding_type'], name='core_schola_level_d34894_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedscholarship',
            unique_together={('user', 'scholarship')},
        ),
    ]
