# Generated by Django 6.0.7 on 2026-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_question_reply_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=20, unique=True)),
                ('label', models.CharField(max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Controls display order, lower shows first.')),
            ],
            options={
                'ordering': ['order', 'label'],
            },
        ),
        migrations.RemoveIndex(
            model_name='scholarship',
            name='core_schola_level_d34894_idx',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='levels',
            field=models.ManyToManyField(blank=True, help_text='Select every level this scholarship funds (most fund more than one).', related_name='scholarships', to='core.level'),
        ),
        migrations.AddIndex(
            model_name='scholarship',
            index=models.Index(fields=['funding_type'], name='core_schola_funding_970063_idx'),
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='level',
        ),
    ]
